"use strict";


const HTTP_STATUS = {
  METHOD_NOT_FOUND: 405,
  OK: 200,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  UNAVAILABLE_FOR_SOME_REASONS: 451,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
  SERVICE_UNAVAILABLE: 503,
};



const APPLICATION_DATA_HEADER_KEY = "x-application-data";


module.exports = {
  HTTP_STATUS,
  APPLICATION_DATA_HEADER_KEY,
};
